# Generated by Django 4.0.4 on 2022-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
